package layout;
import flexbox.Order;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;



public class FlexBoxGUI extends javax.swing.JFrame {

    /**
     * Creates new form FlexBoxGUI
     */  
    
    flexbox.Order ord;
    
    public FlexBoxGUI(flexbox.Order in) {
        initComponents();
        AddNewItem.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        ord = in;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColourButtons = new javax.swing.ButtonGroup();
        AddNewItem = new javax.swing.JFrame();
        GradeSlider = new javax.swing.JSlider();
        ColourRadio0 = new javax.swing.JRadioButton();
        ColourRadio2 = new javax.swing.JRadioButton();
        ColourRadio1 = new javax.swing.JRadioButton();
        SealableCheckbox = new javax.swing.JCheckBox();
        BottomCheckbox = new javax.swing.JCheckBox();
        CornerCheckbox = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        QuantityInput = new javax.swing.JEditorPane();
        WidthInput = new javax.swing.JEditorPane();
        LengthInput = new javax.swing.JEditorPane();
        HeightInput = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CalculateCostButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        AddButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Label_Main = new javax.swing.JLabel();
        Label_CurrOrd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_CurrOrd = new javax.swing.JList<>();
        Label_Total = new javax.swing.JLabel();
        Label_TotalSum = new javax.swing.JLabel();
        Button_AddBox = new javax.swing.JButton();
        Button_CheckOut = new javax.swing.JButton();
        Button_RemoveBox = new javax.swing.JButton();

        AddNewItem.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddNewItem.setTitle("Add New Item");
        AddNewItem.setMinimumSize(new java.awt.Dimension(720, 450));
        AddNewItem.setResizable(false);
        AddNewItem.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                AddNewItemWindowClosing(evt);
            }
        });
        AddNewItem.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GradeSlider.setMajorTickSpacing(1);
        GradeSlider.setMaximum(5);
        GradeSlider.setMinimum(1);
        GradeSlider.setMinorTickSpacing(1);
        GradeSlider.setPaintLabels(true);
        GradeSlider.setSnapToTicks(true);
        GradeSlider.setValue(1);
        AddNewItem.getContentPane().add(GradeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 30));

        ColourButtons.add(ColourRadio0);
        ColourRadio0.setText("No colour");
        ColourRadio0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourRadio0ActionPerformed(evt);
            }
        });
        AddNewItem.getContentPane().add(ColourRadio0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        ColourButtons.add(ColourRadio2);
        ColourRadio2.setText("Two Coloured");
        ColourRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourRadio2ActionPerformed(evt);
            }
        });
        AddNewItem.getContentPane().add(ColourRadio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        ColourButtons.add(ColourRadio1);
        ColourRadio1.setText("Single Coloured");
        ColourRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourRadio1ActionPerformed(evt);
            }
        });
        AddNewItem.getContentPane().add(ColourRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        SealableCheckbox.setText("Sealable");
        AddNewItem.getContentPane().add(SealableCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 100, -1, -1));

        BottomCheckbox.setText("Reinforced");
        BottomCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomCheckboxActionPerformed(evt);
            }
        });
        AddNewItem.getContentPane().add(BottomCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 100, -1, -1));

        CornerCheckbox.setText("Reinforced");
        CornerCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CornerCheckboxActionPerformed(evt);
            }
        });
        AddNewItem.getContentPane().add(CornerCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 100, -1, -1));
        AddNewItem.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 720, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        AddNewItem.getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 720, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Grade");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewItem.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Colour");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewItem.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 135, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bottom");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewItem.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 50, 125, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Corners");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewItem.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 125, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Top");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewItem.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 50, 125, 20));

        CancelButton.setText("Cancel");
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelButtonMousePressed(evt);
            }
        });
        AddNewItem.getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 140, 40));

        QuantityInput.setContentType("int"); // NOI18N
        QuantityInput.setText("1");
        QuantityInput.setAutoscrolls(false);
        QuantityInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityInputKeyTyped(evt);
            }
        });
        AddNewItem.getContentPane().add(QuantityInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 60, 20));

        WidthInput.setContentType("int"); // NOI18N
        WidthInput.setText("1");
        WidthInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WidthInputKeyTyped(evt);
            }
        });
        AddNewItem.getContentPane().add(WidthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 20));

        LengthInput.setContentType("int"); // NOI18N
        LengthInput.setText("1");
        LengthInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LengthInputKeyTyped(evt);
            }
        });
        AddNewItem.getContentPane().add(LengthInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 60, 20));

        HeightInput.setContentType("int"); // NOI18N
        HeightInput.setText("1");
        HeightInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HeightInputKeyTyped(evt);
            }
        });
        AddNewItem.getContentPane().add(HeightInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantity:");
        jLabel8.setPreferredSize(new java.awt.Dimension(62, 15));
        AddNewItem.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 80, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("cm");
        AddNewItem.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 30, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Length:");
        AddNewItem.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 80, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Height:");
        AddNewItem.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 80, -1));

        CalculateCostButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        CalculateCostButton.setText("Calculate");
        CalculateCostButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CalculateCostButtonMousePressed(evt);
            }
        });
        AddNewItem.getContentPane().add(CalculateCostButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 90, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Box Selection");
        jLabel11.setMaximumSize(new java.awt.Dimension(140, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(140, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(140, 17));
        AddNewItem.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceLabel.setText("£0.00");
        AddNewItem.getContentPane().add(PriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 170, 20));
        AddNewItem.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 720, 10));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cost:");
        AddNewItem.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, -1));

        AddButton1.setText("Add To Cart");
        AddButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton1MouseClicked(evt);
            }
        });
        AddNewItem.getContentPane().add(AddButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 140, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Width:");
        AddNewItem.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("cm");
        AddNewItem.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 30, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("cm");
        AddNewItem.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 30, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlexBox");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(736, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(736, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Main.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Label_Main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Main.setText("FlexBox");
        getContentPane().add(Label_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 736, -1));

        Label_CurrOrd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_CurrOrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_CurrOrd.setText("Current Order:");
        Label_CurrOrd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Label_CurrOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 736, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 736, 5));

        List_CurrOrd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(List_CurrOrd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 75, 600, 300));

        Label_Total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_Total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_Total.setText("Total:");
        getContentPane().add(Label_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 139, -1));

        Label_TotalSum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_TotalSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_TotalSum.setText("£0.00");
        getContentPane().add(Label_TotalSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 138, -1));

        Button_AddBox.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        Button_AddBox.setText("+");
        Button_AddBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Button_AddBoxMousePressed(evt);
            }
        });
        getContentPane().add(Button_AddBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 80, 45, 45));

        Button_CheckOut.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Button_CheckOut.setText("Check out");
        getContentPane().add(Button_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 450, 180, 60));

        Button_RemoveBox.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        Button_RemoveBox.setText("-");
        Button_RemoveBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Button_RemoveBoxMousePressed(evt);
            }
        });
        getContentPane().add(Button_RemoveBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 130, 45, 45));

        getAccessibleContext().setAccessibleDescription("Desktop application for placing orders");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewItemWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AddNewItemWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_AddNewItemWindowClosing

    private void CancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMousePressed
        this.setVisible(true);
        AddNewItem.setVisible(false);
    }//GEN-LAST:event_CancelButtonMousePressed

    private void ColourRadio0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourRadio0ActionPerformed
        if (ColourRadio0.isSelected()){
            setGradeSlider(1, 3);
            disableReinforcments();
        }
    }//GEN-LAST:event_ColourRadio0ActionPerformed

    private void ColourRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourRadio1ActionPerformed
        if (ColourRadio1.isSelected()){
            setGradeSlider(2, 4);
            disableReinforcments();
        }
    }//GEN-LAST:event_ColourRadio1ActionPerformed

    private void ColourRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourRadio2ActionPerformed
        if (ColourRadio2.isSelected()){
            setGradeSlider(2, 5);
            BottomCheckbox.setEnabled(true);
            CornerCheckbox.setEnabled(true);
            BottomCheckbox.setSelected(false);
            CornerCheckbox.setSelected(false);
        }
    }//GEN-LAST:event_ColourRadio2ActionPerformed

    private void CornerCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CornerCheckboxActionPerformed
        if (CornerCheckbox.isSelected()){
            GradeSlider.setMinimum(3);
            GradeSlider.setValue(3);
            BottomCheckbox.setSelected(true);
        }
        else {
            GradeSlider.setMinimum(2);
            GradeSlider.setValue(2);
        }
    }//GEN-LAST:event_CornerCheckboxActionPerformed

    private void BottomCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomCheckboxActionPerformed
        if (!BottomCheckbox.isSelected()){
            setGradeSlider(2, 5);
            CornerCheckbox.setSelected(false);
        }
        else setGradeSlider(2, 5);
    }//GEN-LAST:event_BottomCheckboxActionPerformed

    private void WidthInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WidthInputKeyTyped
        if (WidthInput.getText().length() <= 5) {
            isNumberInput(evt);
        } else evt.consume();
    }//GEN-LAST:event_WidthInputKeyTyped

    private void LengthInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LengthInputKeyTyped
        if (LengthInput.getText().length() <= 5) {
            isNumberInput(evt);
        } else evt.consume();
    }//GEN-LAST:event_LengthInputKeyTyped

    private void HeightInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HeightInputKeyTyped
        if (HeightInput.getText().length() <= 5) {
            isNumberInput(evt);
        } else evt.consume();
    }//GEN-LAST:event_HeightInputKeyTyped

    private void QuantityInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityInputKeyTyped
        if (QuantityInput.getText().length() <= 5) {
            isNumberInput(evt);
        } else evt.consume();
    }//GEN-LAST:event_QuantityInputKeyTyped

    private void CalculateCostButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculateCostButtonMousePressed
        ord.setPriceLabel();
    }//GEN-LAST:event_CalculateCostButtonMousePressed

    private void AddButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseClicked
        confirmBox();
    }//GEN-LAST:event_AddButton1MouseClicked

    private void Button_RemoveBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_RemoveBoxMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_RemoveBoxMousePressed

    private void Button_AddBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_AddBoxMousePressed
        AddNewItem.setLocationRelativeTo(null);
        AddNewItem.setVisible(true);
        this.setVisible(false);
        GradeSlider.setMinimum(1);
        GradeSlider.setMaximum(3);
        GradeSlider.setValue(1);
        disableReinforcments();
        ColourRadio0.setSelected(true);
        WidthInput.setText("0");
        HeightInput.setText("0");
        LengthInput.setText("0");
        QuantityInput.setText("1");
        PriceLabel.setText("£0.00");
        SealableCheckbox.setSelected(false);
    }//GEN-LAST:event_Button_AddBoxMousePressed

    private void confirmBox()
    {
        double price = ord.calculatePrice();
        if (price < 0.01){
            JOptionPane.showConfirmDialog(null, "The Selected Options for a box"
                    + " can not be provided.\n Please change the properties and "
                    + "try again.", "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else {
            String text = "Add the following (" + ord.getCurrentBoxQuantity() + ") box(-es) to your order:\n"
                    + "Width: " + ord.getCurrentBoxWidth() + "cm\n"
                    + "Height: " + ord.getCurrentBoxHeight() + "cm\n"
                    + "Length: " + ord.getCurrentBoxLength() + "cm\n"
                    + "Grade: " + ord.getCurrentBoxGrade() + "\n"
                    + "Reinforced Corners: " + ord.hasThickCorners() + "\n"
                    + "Reinforced Bottom: " + ord.hasThickBottom() + "\n"
                    + "Sealable: " + ord.isCurrentBoxSealable() + "\n\n Total: £" + price;
            int dialogResult = JOptionPane.showConfirmDialog(null, text, "Confirm Box(-es)", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(dialogResult == JOptionPane.OK_OPTION){
                this.setVisible(true);
                AddNewItem.setVisible(false);
                //TO DO: Add Boxes to order.
            }
        }
    }
    
    private void isNumberInput(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }
    
    private void disableReinforcments(){
        BottomCheckbox.setEnabled(false);
        CornerCheckbox.setEnabled(false);
        BottomCheckbox.setSelected(false);
        CornerCheckbox.setSelected(false);
    }
    
    private void setGradeSlider(int min, int max){
        GradeSlider.setMinimum(min);
        GradeSlider.setMaximum(max);
        GradeSlider.setValue(min);
    }
    
    public void getChoiceValues(ArrayList values){
        values.clear();
        values.add(GradeSlider.getValue());
        
        if (ColourRadio0.isSelected()) { values.add(0); }
        else if (ColourRadio1.isSelected()) { values.add(1); }
        else { values.add(2); }
        
        if (CornerCheckbox.isSelected()) { values.add(true); } else { values.add(false); }
        if (BottomCheckbox.isSelected()) { values.add(true); } else { values.add(false); }
        if (SealableCheckbox.isSelected()) { values.add(true); } else { values.add(false); }
        
        values.add(Integer.valueOf(LengthInput.getText()));
        values.add(Integer.valueOf(WidthInput.getText()));
        values.add(Integer.valueOf(HeightInput.getText()));
        values.add(Integer.valueOf(QuantityInput.getText()));
    }
    
    public void emptyFieldError(){
        String message = "One or a few of the following fields are empty:\n"
                + "Width\n"
                + "Length\n"
                + "Height\n"
                + "Quantity\n\n"
                + "Please check your input and try again.";
        JOptionPane.showMessageDialog(this, message, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton1;
    private javax.swing.JFrame AddNewItem;
    private javax.swing.JCheckBox BottomCheckbox;
    private javax.swing.JButton Button_AddBox;
    private javax.swing.JButton Button_CheckOut;
    private javax.swing.JButton Button_RemoveBox;
    private javax.swing.JButton CalculateCostButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.ButtonGroup ColourButtons;
    private javax.swing.JRadioButton ColourRadio0;
    private javax.swing.JRadioButton ColourRadio1;
    private javax.swing.JRadioButton ColourRadio2;
    private javax.swing.JCheckBox CornerCheckbox;
    private javax.swing.JSlider GradeSlider;
    public javax.swing.JEditorPane HeightInput;
    private javax.swing.JLabel Label_CurrOrd;
    private javax.swing.JLabel Label_Main;
    private javax.swing.JLabel Label_Total;
    private javax.swing.JLabel Label_TotalSum;
    public javax.swing.JEditorPane LengthInput;
    private javax.swing.JList<String> List_CurrOrd;
    public javax.swing.JLabel PriceLabel;
    public javax.swing.JEditorPane QuantityInput;
    private javax.swing.JCheckBox SealableCheckbox;
    public javax.swing.JEditorPane WidthInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
